spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reviewer_api
    username: root
    password: root
  main:
    allow-circular-references: true

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

server:
  port: 8056

  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}

management:
  endpoints:
    web:
      exposure:
        include:  "*"
              
      cors:
        allowed-headers:
        - "*"
        allowed-origins:
        - "*"
        allowed-methods:
        - "*"
        allow-credentials: true


