spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reviewer_api
    username: root

  main:
    allow-circular-references: true

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

  mail:
    host: rb-smtp-auth.rbesz01.com
    port: 25
    username: bxfrca@bosch.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            trust: rb-smtp-auth.rbesz01.com
          auth: true
          starttls:
            enable: true


security:
  oauth2:
    client:
      provider:
        azure-ad:
          authorization-uri: ${AUTHORIZATION_URI}
          token-uri: ${TOKEN_URI}
          jwk-set-uri: ${JWK_SET_URI}

      registration:
        azure-client:
          provider: azure-ad
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          authorization-grant-type: authorization_code
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          scope: openid

server:
  port: 8056

  error:
    include-stacktrace: never

 
api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}

management:
  endpoints:
    web:
      exposure:
        include:  "*"
              
      cors:
        allowed-headers:
        - "*"
        allowed-origins:
        - "*"
        allowed-methods:
        - "*"
        allow-credentials: true


